# Generated by Django 6.0.4 on 2026-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount'), ('FREE_DELIVERY', 'Free Delivery')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('max_total_uses', models.IntegerField(blank=True, null=True)),
                ('max_per_customer', models.IntegerField(default=1)),
                ('used_count', models.IntegerField(default=0)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('all_products', models.BooleanField(default=True)),
                ('exclude_sale_items', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('specific_categories', models.ManyToManyField(blank=True, to='products.category')),
                ('specific_products', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='promotions/flash_sales/')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('show_countdown', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(related_name='flash_sales', to='products.product')),
            ],
        ),
    ]
