# Generated by Django 4.2.29 on 2026-05-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MANAGER', 'Manager'), ('SALES_AGENT', 'Sales Agent'), ('DISPATCHER', 'Dispatcher'), ('FUNDI', 'Fundi (Technician)'), ('DRIVER', 'Driver'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('ACCOUNTANT', 'Accountant')], default='SALES_AGENT', max_length=50),
        ),
    ]
